ALTER TABLE orders ALTER COLUMN first_name DROP NOT NULL;
ALTER TABLE orders ALTER COLUMN last_name DROP NOT NULL;
ALTER TABLE orders ALTER COLUMN address DROP NOT NULL;
ALTER TABLE orders ALTER COLUMN city DROP NOT NULL;
ALTER TABLE orders ALTER COLUMN postal_code DROP NOT NULL;